### ISSUE TITLE
steps option in the second example

### ISSUE THREAD

**Issue by ksaagar** [carlganz/rintrojs#13]
To make the steps option in the second example work as expected, I tried to put a # in front of the div element name and it worked as expected

server <- shinyServer(function(input, output, session) {

  steps <- reactive(data.frame(element = c(NA,**"#btn"),**
                               intro = c(input$intro,"This is a button")))

  observeEvent(input$btn,{
    introjs(session,options = list(steps=steps()))

  })

})

**Comment by carlganz** [comment]
It works for me with either `btn` or `#btn`. What isn't working as expected?

This app is the exact code in the example: https://carlganz.shinyapps.io/rintroprogrammatic/

Thanks!

**Comment by ksaagar** [comment]
This is how I see it though. I would have expected that the box would
appear on the element, no?

[image: Inline image 5]


*Kshira Saagar*   Head of Insights/Analytics | Datalicious Pty Ltd
<http://www.datalicious.com>
*e: *ksaagar@datalicious.com   *p: *+612 8999 5955
*m: *+61 412 031 346   *w: *datalicious.com <http://www.datalicious.com>
Level 8, 90 Arthur Street North Sydney NSW 2060

<http://data.li/1Gscj0C>   <http://data.li/1WdeuXv>
<http://data.li/1kGJsM5>   <http://data.li/1LQEjYz>
<http://data.li/1Nv4oze>   <http://data.li/1O243ai>
<http://data.li/1k42ETs>

<http://www.datalicious.com/media-budgets-index-comparing-media-budget-allocation-to-media-consumption/?signature=ksaagar@datalicious.com&utm_campaign=media_budgets_index_2016&utm_medium=email&utm_source=ksaagar@datalicious.com>

**Comment by carlganz** [comment]
D'oh. Of course. Thank you
