### ISSUE TITLE
Latest Dev version does not respond to 'Done' at the end of intro

### ISSUE THREAD

**Issue by happyshows** [carlganz/rintrojs#18]
prod version is fine but not for dev. somehow the last step js is not triggered.

```
  observeEvent(input$al_help,
               introjs(session, options = list("nextLabel"="Next","prevLabel"="Previous","skipLabel"="Exit"),
                       events = list("oncomplete"='alert("Ready to Roll")'))
  )
````

**Comment by carlganz** [comment]
Yeah,

Breaking change was made in the dev version. If you take a look at the [news](https://github.com/carlganz/rintrojs/blob/master/NEWS.md) you'll see that javascript code for events must be wrapped in `I()` for the underlying JSON to be correct.

So for your example:

```{R}
observeEvent(input$al_help,
               introjs(session, options = list("nextLabel"="Next","prevLabel"="Previous","skipLabel"="Exit"),
                       events = list("oncomplete"=I('alert("Ready to Roll")')))
  )
```
Should do the trick. 

Let me know if it doesn't.

**Comment by happyshows** [comment]
It looks ok except that when you click the dots  (which allows you to jump directly to any step), it triggers the js immediately, I don't think that's an expected behavior.

**Comment by carlganz** [comment]
I can't reproduce that behavior. Please provide a full reproducible example. The dots do have some problems pointed out in #16 so I do not currently recommend using them.

**Comment by carlganz** [comment]
@happyshows Sorry for the delay. I believe this is resolved now. Please try the latest version on github and let me know if there are any problems.

Kind regards,
Carl

**Comment by fmmattioni** [comment]
I guess I have just run into the same problem as @happyshows was having.

The issue is that when trying to use [shinyjs](https://github.com/daattali/shinyjs) on the `events` argument in `rintrojs::introjs()`, the JS function is triggered immediately, and not in the specified event.

reprex:

```
library(shiny)
library(rintrojs)

ui <- shinyUI(fluidPage(
  introjsUI(),
  shinyjs::useShinyjs(),
  mainPanel(
    textInput("intro","Enter an introduction"),
    actionButton("btn","Press me")
  )
)
)

server <- shinyServer(function(input, output, session) {
  
  steps <- reactive(data.frame(element = c(NA,"#btn"),
                               intro = c(input$intro,"This is a button")))
  
  observeEvent(input$btn,{
    introjs(
      session,
      options = list(steps = steps()),
      events = list(onexit = shinyjs::hide(id = "intro"))
    )
    
  })
  
})

# Run the application 
shinyApp(ui = ui, server = server)
```
