### ISSUE TITLE
Allow user to define the position of intro div

### ISSUE THREAD

**Issue by happyshows** [carlganz/rintrojs#19]
Sometimes when the original div is tall, the intro div showed below that. It would be nice if user can decide to move the intro div to top

**Comment by carlganz** [comment]
If you can provide a reproducible example I may be able to help.

**Comment by happyshows** [comment]
for example, I want the intro box to show on left-top or right -top of the div.

![image](https://cloud.githubusercontent.com/assets/3208181/24806083/554cd542-1b79-11e7-8e4a-2eb5783bc6ac.png)

**Comment by carlganz** [comment]
@happyshows I have added a `data.position` parameter to `introBox` that lets you specify the position of the intro.

You can also define the position of the box from the server by passing options to `introjs`.

Thanks for the suggestion. 

Kind regards,
Carl

**Comment by carlganz** [comment]
6072275
