### ISSUE TITLE
Not loaded on shinyapps.io

### ISSUE THREAD

**Issue by georgemirandajr** [carlganz/rintrojs#21]
The introBox functions work fine when I run them from R Studio and view my app in the browser. However, I see that once it is loaded on shinyapps.io there is an error (see below) from shinyapps that says it cannot find introjsUI(), even though "rintrojs" is called in my app along with other packages.  

`ERROR: could not find function "introjsUI"`

Should it work fine with shinyapps.io?

**Comment by carlganz** [comment]
Just a guess but does your UI file include `library(rintrojs)`?

**Comment by georgemirandajr** [comment]
How embarrassing. The other packages I use in the app are called with require(), which has worked fine for me. When I use library() shinyapps picks up that package and all is well in the world.
