### ISSUE TITLE
Location of data.step number

### ISSUE THREAD

**Issue by jamesonl** [carlganz/rintrojs#26]
Hello!

I want to start by mentioning that this package has been tremendously helpful in providing me a way to scale the training and enablement of many, many users on what would traditionally take hours to explain to people - THANK YOU!!

I am using this within a shiny dashboard (specifically, the sidebar to highlight functionality of various tabs). However, as I'm not able to specify the position of the red-circled data.step, the value becomes lost in the sidebar (and the user does not know the order of the suggestions).

Is there a way to turn off this feature, or specify the location that this appears (top-left, top-right, bottom-left, bottom-right)?

**Comment by carlganz** [comment]
Thanks for the kind words!

Could you provide a minimal reproducible example? I am pretty sure I know what you are saying, but MRE help clarify.

**Comment by jamesonl** [comment]
Sure! This is the left-most side of my dashboard, with the snapshot taken with the browser expanded to full-screen.
<img width="434" alt="screen shot 2017-11-27 at 5 23 55 pm" src="https://user-images.githubusercontent.com/6571170/33297796-de7490ae-d397-11e7-859d-e6e6511c97ba.png">

As you can see, the red bubble is cut off and I don't have a way to adjust its location in order to make it visible. If there was a way to specify the location of the bubble (top-left, top-right, bottom-left, bottom-right), that would be amazing.

**Comment by jamesonl** [comment]
I'm working on putting together an MRE to attach, but wanted to also provide a basic visual.

**Comment by carlganz** [comment]
I get what the problem is. Looking through the intro.js documentation (https://introjs.com/docs/intro/options/) would suggest that the location of the step number isn't an option parameter, so some sort of custom js/css solution would probably need to be hacked together. This seems like something intro.js should be able to do, so I encourage you to file an issue upstream with intro.js.
