### ISSUE TITLE
Adding to Intro.js 

### ISSUE THREAD

**Issue by afshinm** [carlganz/rintrojs#3]
Hey guys,

Intro.js author's here. Can I add your lib to the main Intro.js's readme?

**Comment by carlganz** [comment]
Hey Afshin,

Thanks for the wonderful JS library. This is definitely still a work-in-progress, but you can add it to the Intro.js readme if you'd like. 

Kind Regards,
Carl

**Comment by afshinm** [comment]
cheers, thanks for this. Will add this then.

**Comment by carlganz** [comment]
Hey @afshinm, I am planning on submitting this package to [CRAN](https://cran.r-project.org/), which is the official R package repository. 

Once it is posted I will make a PR to introjs to add a link to your readme.

Thanks again for the wonderful javascript library.

**Comment by afshinm** [comment]
hey @carlganz. Just noticed you have added this to CRAN, good job! 

Let me know when you want to add this to the readme. thanks a lot!

**Comment by afshinm** [comment]
PS: https://cran.r-project.org/web/packages/rintrojs/rintrojs.pdf

**Comment by afshinm** [comment]
thanks!
