### ISSUE TITLE
Interactions with bsModals not working

### ISSUE THREAD

**Issue by ArunSharma93** [carlganz/rintrojs#32]
All ui's related to bsModals are not picked up. Here my stackoverflow post about the issue: https://stackoverflow.com/questions/50997367/r-introjs-bsmodal

**Comment by LukasK13** [comment]
I was able to fix the issue by adding

```
.introjs-fixParent.modal {
    z-index:1050 !important;  
}
```
to my CSS. Hope this helps.

**Comment by carlganz** [comment]
Thanks @LukasK13
