### ISSUE TITLE
Hint position when switching shinydashboard tabs

### ISSUE THREAD

**Issue by eroten** [carlganz/rintrojs#34]
I've added six hints to my app over specific charts and I have been using the readCallBack function to tour over different tabs. When the app loads, the hints on the first tab are shown in the correct places. However, when you go from the first tab to the second tab, the first tab hints keep their original location on the page and the second tab hints do not appear. 

When I inspect the page, the first tab hints are hidden and the second tab hints are in their correct location. If you go from the second tab back to the first tab, the second tab hints keep their original location on the page, and the first tab hints do not re-appear. 

I have tried this in Chrome and Firefox and have tried changing position values in CSS on classes 'introjs-hints' and 'introjs-hint', such as changing position from absolute to relative, unset, and fixed. None of these fixes have solved the problem. 

[This link](https://imgur.com/28cGJTd) is to a gif displaying the problem in the full app. 
I am using Firefox (61.0.2 64-bit). This is my sessioninfo() (minus locale):
```
> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] htmlwidgets_1.2.1    shinyWidgets_0.4.3   rintrojs_0.2.1       shinydashboard_0.7.0
[5] shiny_1.1.0          sp_1.3-1            

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.18    lattice_0.20-35 digest_0.6.15   later_0.7.3     mime_0.5       
 [6] grid_3.5.0      R6_2.2.2        jsonlite_1.5    xtable_1.8-2    magrittr_1.5   
[11] rlang_0.2.1     promises_1.0.1  leaflet_2.0.2   tools_3.5.0     crosstalk_1.0.0
[16] yaml_2.2.0      httpuv_1.4.5    compiler_3.5.0  htmltools_0.3.6             

```

[Here](https://gist.github.com/eroten/0e22131c8ab2ea91361a2f5ae25289c0) is a gist with a reproducible example of the issue. 

Hopefully, this is enough information to get started!

**Comment by teshomem** [comment]
@eroten did you find a solution for this?

**Comment by carlganz** [comment]
hmmm, if my memory serves me correctly intro.js has issues dealing with DOM elements that aren't rendered when intro.js is initialized. I think your best bet here is to generate your hints from the server side with the `hintjs` inside an observe that reacts to changes in the selected tab.

Let me know if that works!

**Comment by carlganz** [comment]
Unfortunately all elements in a intro.js tour must exist in the DOM when the tour is initiated so you will have to add the hints from the server side and trigger that whenever the tabs are switched. Hope that helps.
