### ISSUE TITLE
License.txt

### ISSUE THREAD

**Issue by brylie** [carlganz/rintrojs#8]
I am reviewing this package as part of a [submission to the Journal of Open Source Software](https://github.com/openjournals/joss-reviews/issues/63).

As part of my review, I am instructed to locate a license file for the sourcecode. Where can I locate the LICENSE.text, or equivalent file for your wrapper package code?

**Comment by arfon** [comment]
@brylie - R packages usually include this in the `DESCRIPTION` file (see [here](https://github.com/carlganz/rintrojs/blob/7c069348b53a017ea3ef39a42b5f9a0e91bac371/DESCRIPTION#L13)). While this isn't ideal, CRAN (the R package manager) won't permit plain text LICENSE files.

**Comment by carlganz** [comment]
I can add a licence file to the github repo if you'd like.

Thanks for the review everyone!

**Comment by arfon** [comment]
> I can add a licence file to the github repo if you'd like.

Sounds good to me @carlganz. Thanks.

**Comment by carlganz** [comment]
Added license

**Comment by graingert** [comment]
FYI this should be the AGPL-3

**Comment by carlganz** [comment]
Thanks

**Comment by carlganz** [comment]
ae3137d
